name = "proven-provider"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Add account_id and route configurations
account_id = "131aa272033d31af519cb9ce93df9bd4"
workers_dev = true

[vars]
# Add your environment variables here 